/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.ruoyi.common.core.web.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.ruoyi.common.core.web.domain.BaseEntity;
import java.util.Date;
import java.util.Map;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class BaseEntity_SSTest extends BaseEntity_SSTest_scaffolding {
// allCoveredLines:[16, 47, 52, 53, 57, 62, 63, 67, 72, 73, 77, 82, 83, 87, 92, 93, 97, 102, 103, 107, 109, 111, 116, 117]

  @Test(timeout = 4000)
  public void test_getCreateBy_00()  throws Throwable  {
      //caseID:355565f67ebf5454fb21a5789d29782b
      //CoveredLines: [16, 57]
      //Assert: assertNull(method_result);
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: getCreateBy
      String string0 = baseEntity0.getCreateBy();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getCreateTime_01()  throws Throwable  {
      //caseID:d41bbfce5c0fd709c437561b3f47c98d
      //CoveredLines: [16, 67]
      //Assert: assertNull(method_result);
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: getCreateTime
      Date date0 = baseEntity0.getCreateTime();
      
      //Test Result Assert
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test_getParams_02()  throws Throwable  {
      //caseID:69477029433ff503de85ce3efa898d00
      //CoveredLines: [16, 107, 111]
      //Assert: assertFalse(method_result.isEmpty());
      
      BaseEntity baseEntity0 = new BaseEntity();
      //mock map0
      Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("").when(map0).toString();
      
      PrivateAccess.setVariable((Class<?>) BaseEntity.class, baseEntity0, "params", (Object) map0);
      
      //Call method: getParams
      Map<String, Object> map1 = baseEntity0.getParams();
      
      //Test Result Assert
      assertFalse(map1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_getParams_03()  throws Throwable  {
      //caseID:1ea6bc8c954f7116e6ef0ccd4605238e
      //CoveredLines: [16, 107, 109, 111]
      //Assert: assertNotNull(method_result);
      //Assert: assertEquals(0, method_result.size());
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: getParams
      Map<String, Object> map0 = baseEntity0.getParams();
      
      //Test Result Assert
      assertNotNull(map0);
      
      //Test Result Assert
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test_getRemark_04()  throws Throwable  {
      //caseID:34b5023ba07365bdeb5a9455c56e9e84
      //CoveredLines: [16, 97]
      //Assert: assertNull(method_result);
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: getRemark
      String string0 = baseEntity0.getRemark();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getSearchValue_05()  throws Throwable  {
      //caseID:60fd7e638895f89e4a576f57f9c412b0
      //CoveredLines: [16, 47]
      //Assert: assertNull(method_result);
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: getSearchValue
      String string0 = baseEntity0.getSearchValue();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getUpdateBy_06()  throws Throwable  {
      //caseID:28b2803e14367b858915732fa656c1c1
      //CoveredLines: [16, 77]
      //Assert: assertNull(method_result);
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: getUpdateBy
      String string0 = baseEntity0.getUpdateBy();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getUpdateTime_07()  throws Throwable  {
      //caseID:345ae10cc6248ff88314fdc46b74bce5
      //CoveredLines: [16, 87]
      //Assert: assertNull(method_result);
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: getUpdateTime
      Date date0 = baseEntity0.getUpdateTime();
      
      //Test Result Assert
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test_setCreateBy_08()  throws Throwable  {
      //caseID:86dbb1dd4448cf93c5c8df11eaa9288e
      //CoveredLines: [16, 62, 63]
      //Input_0_String: 1
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: setCreateBy
      baseEntity0.setCreateBy("1");
      
      //Test Result Assert
      assertNull(baseEntity0.getUpdateBy());
  }

  @Test(timeout = 4000)
  public void test_setCreateTime_09()  throws Throwable  {
      //caseID:17a85ba5124ec7f4ca881c55cb1c040b
      //CoveredLines: [16, 72, 73]
      //Input_0_Date: {}
      
      BaseEntity baseEntity0 = new BaseEntity();
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setCreateTime
      baseEntity0.setCreateTime(date0);
      
      //Test Result Assert
      assertNull(baseEntity0.getRemark());
  }

  @Test(timeout = 4000)
  public void test_setParams_10()  throws Throwable  {
      //caseID:194b7054789f5893cbe9936d0fbc1e3e
      //CoveredLines: [16, 116, 117]
      //Input_0_Map<String, Object>: {}
      
      BaseEntity baseEntity0 = new BaseEntity();
      //mock map0
      Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setParams
      baseEntity0.setParams(map0);
      
      //Test Result Assert
      assertNull(baseEntity0.getSearchValue());
  }

  @Test(timeout = 4000)
  public void test_setRemark_11()  throws Throwable  {
      //caseID:3f6be3a67861b64919e57b3f71ed686b
      //CoveredLines: [16, 102, 103]
      //Input_0_String: 1
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: setRemark
      baseEntity0.setRemark("1");
      
      //Test Result Assert
      assertNull(baseEntity0.getSearchValue());
  }

  @Test(timeout = 4000)
  public void test_setSearchValue_12()  throws Throwable  {
      //caseID:cb9ea3a3305be3cf479eafe1e1c0d2ef
      //CoveredLines: [16, 52, 53]
      //Input_0_String: -@ gLX
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: setSearchValue
      baseEntity0.setSearchValue("-@ gLX");
      
      //Test Result Assert
      assertNull(baseEntity0.getCreateBy());
  }

  @Test(timeout = 4000)
  public void test_setUpdateBy_13()  throws Throwable  {
      //caseID:a1c95ec034d12b9f288114cb0ff5af06
      //CoveredLines: [16, 82, 83]
      //Input_0_String: 1
      
      BaseEntity baseEntity0 = new BaseEntity();
      
      //Call method: setUpdateBy
      baseEntity0.setUpdateBy("1");
      
      //Test Result Assert
      assertNull(baseEntity0.getRemark());
  }

  @Test(timeout = 4000)
  public void test_setUpdateTime_14()  throws Throwable  {
      //caseID:59d1f9dbe625dfbcf1823648d2d95d0b
      //CoveredLines: [16, 92, 93]
      //Input_0_Date: {}
      
      BaseEntity baseEntity0 = new BaseEntity();
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setUpdateTime
      baseEntity0.setUpdateTime(date0);
      
      //Test Result Assert
      assertNull(baseEntity0.getCreateBy());
  }
}
