/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.ruoyi.common.core.web.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.ruoyi.common.core.web.domain.TreeEntity;
import java.util.LinkedList;
import java.util.List;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class TreeEntity_SSTest extends TreeEntity_SSTest_scaffolding {
// allCoveredLines:[11, 28, 32, 37, 38, 42, 47, 48, 52, 57, 58, 62, 67, 68, 72, 77, 78]

  @Test(timeout = 4000)
  public void test_getAncestors_0()  throws Throwable  {
      //caseID:ddfc9b9b638a5e43fa7bd6c9b5b66501
      //CoveredLines: [11, 28, 62]
      //Assert: assertNull(method_result);
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getAncestors
      String string0 = treeEntity0.getAncestors();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getChildren_1()  throws Throwable  {
      //caseID:b1ed690749b31828088ecb234b3dfa9c
      //CoveredLines: [11, 28, 72]
      //Assert: assertEquals(0, method_result.size());
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getChildren
      List<?> list0 = treeEntity0.getChildren();
      
      //Test Result Assert
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test_getOrderNum_2()  throws Throwable  {
      //caseID:60a33c463466e65393089d456c916fce
      //CoveredLines: [11, 28, 52]
      //Assert: assertNull(method_result);
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getOrderNum
      Integer integer0 = treeEntity0.getOrderNum();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test_getParentId_3()  throws Throwable  {
      //caseID:f0a342d5f814c83ec235a74882aa8567
      //CoveredLines: [11, 28, 42]
      //Assert: assertNull(method_result);
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getParentId
      Long long0 = treeEntity0.getParentId();
      
      //Test Result Assert
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test_getParentName_4()  throws Throwable  {
      //caseID:cd2cd378da4c99589f774e566ec25e8d
      //CoveredLines: [11, 28, 32]
      //Assert: assertNull(method_result);
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getParentName
      String string0 = treeEntity0.getParentName();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_setAncestors_5()  throws Throwable  {
      //caseID:e823541ec0a4f3af0f13118de7dc9fea
      //CoveredLines: [11, 28, 67, 68]
      //Input_0_String: 1.0
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: setAncestors
      treeEntity0.setAncestors("1.0");
      
      //Test Result Assert
      assertEquals("1.0", treeEntity0.getAncestors());
  }

  @Test(timeout = 4000)
  public void test_setChildren_6()  throws Throwable  {
      //caseID:d82a3a569e0ce1124c8820022248e91c
      //CoveredLines: [11, 28, 77, 78]
      //Input_0_List<?>: linkedList0
      
      TreeEntity treeEntity0 = new TreeEntity();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      
      //Call method: setChildren
      treeEntity0.setChildren(linkedList0);
      
      //Test Result Assert
      assertNull(treeEntity0.getParentId());
  }

  @Test(timeout = 4000)
  public void test_setOrderNum_7()  throws Throwable  {
      //caseID:170d4c3e889e4c96c874f8020c003c5c
      //CoveredLines: [11, 28, 57, 58]
      //Input_0_Integer: 2112
      
      TreeEntity treeEntity0 = new TreeEntity();
      Integer integer0 = new Integer(2112);
      
      //Call method: setOrderNum
      treeEntity0.setOrderNum(integer0);
      
      //Test Result Assert
      assertNull(treeEntity0.getParentId());
  }

  @Test(timeout = 4000)
  public void test_setParentId_8()  throws Throwable  {
      //caseID:8e15de8ae66344f943b6d7d8ad6dd4c1
      //CoveredLines: [11, 28, 47, 48]
      //Input_0_Long: 0
      
      TreeEntity treeEntity0 = new TreeEntity();
      Long long0 = new Long(0);
      
      //Call method: setParentId
      treeEntity0.setParentId(long0);
      
      //Test Result Assert
      assertNull(treeEntity0.getSearchValue());
  }

  @Test(timeout = 4000)
  public void test_setParentName_9()  throws Throwable  {
      //caseID:f933536d5cdeebb82c3989d062c0c786
      //CoveredLines: [11, 28, 37, 38]
      //Input_0_String: 1
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: setParentName
      treeEntity0.setParentName("1");
      
      //Test Result Assert
      assertNull(treeEntity0.getAncestors());
  }
}
