/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.ruoyi.common.core.web.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.ruoyi.common.core.web.domain.TreeEntity;
import java.util.List;
import java.util.Stack;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class TreeEntity_SSTest extends TreeEntity_SSTest_scaffolding {
// allCoveredLines:[11, 28, 32, 37, 38, 42, 47, 48, 52, 57, 58, 62, 67, 68, 72, 77, 78]

  @Test(timeout = 4000)
  public void test_getAncestors_0()  throws Throwable  {
      //caseID:2372c64ed3ad3d56c19f23254ce92f90
      //CoveredLines: [11, 28, 62]
      //Assert: assertNull(method_result);
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getAncestors
      String string0 = treeEntity0.getAncestors();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getChildren_1()  throws Throwable  {
      //caseID:146b331ba618e17352dd262e755c0c2e
      //CoveredLines: [11, 28, 72]
      //Assert: assertEquals(0, method_result.size());
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getChildren
      List<?> list0 = treeEntity0.getChildren();
      
      //Test Result Assert
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test_getOrderNum_2()  throws Throwable  {
      //caseID:f5ceac7db2ba1c07436195984e2ec388
      //CoveredLines: [11, 28, 52]
      //Assert: assertNull(method_result);
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getOrderNum
      Integer integer0 = treeEntity0.getOrderNum();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test_getParentId_3()  throws Throwable  {
      //caseID:160a55a29a3af5484d1be72265fbe6dc
      //CoveredLines: [11, 28, 42]
      //Assert: assertNull(method_result);
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getParentId
      Long long0 = treeEntity0.getParentId();
      
      //Test Result Assert
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test_getParentName_4()  throws Throwable  {
      //caseID:d1faefb59b930663e181c8f3bd839d70
      //CoveredLines: [11, 28, 32]
      //Assert: assertNull(method_result);
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: getParentName
      String string0 = treeEntity0.getParentName();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_setAncestors_5()  throws Throwable  {
      //caseID:b885de7e5d504eba529631234b53b2e7
      //CoveredLines: [11, 28, 67, 68]
      //Input_0_String: 
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: setAncestors
      treeEntity0.setAncestors("");
      
      //Test Result Assert
      assertNull(treeEntity0.getParentId());
  }

  @Test(timeout = 4000)
  public void test_setChildren_6()  throws Throwable  {
      //caseID:7476f3e85122d1d1e500c231ee21573c
      //CoveredLines: [11, 28, 77, 78]
      //Input_0_List<?>: stack0
      
      TreeEntity treeEntity0 = new TreeEntity();
      Stack<Integer> stack0 = new Stack<Integer>();
      
      //Call method: setChildren
      treeEntity0.setChildren(stack0);
      
      //Test Result Assert
      assertTrue(stack0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_setOrderNum_7()  throws Throwable  {
      //caseID:9b1ff4b3f3d3a4fcc02345bd5ce365a7
      //CoveredLines: [11, 28, 57, 58]
      //Input_0_Integer: 0
      
      TreeEntity treeEntity0 = new TreeEntity();
      Integer integer0 = new Integer(0);
      
      //Call method: setOrderNum
      treeEntity0.setOrderNum(integer0);
      
      //Test Result Assert
      assertNull(treeEntity0.getSearchValue());
  }

  @Test(timeout = 4000)
  public void test_setParentId_8()  throws Throwable  {
      //caseID:5e6939daf639741f555e072f1bd1691c
      //CoveredLines: [11, 28, 47, 48]
      //Input_0_Long: 0
      
      TreeEntity treeEntity0 = new TreeEntity();
      Long long0 = new Long(0);
      
      //Call method: setParentId
      treeEntity0.setParentId(long0);
      
      //Test Result Assert
      assertNull(treeEntity0.getCreateBy());
  }

  @Test(timeout = 4000)
  public void test_setParentName_9()  throws Throwable  {
      //caseID:5cccf45565a42749d2dd7c56b98a425b
      //CoveredLines: [11, 28, 37, 38]
      //Input_0_String: Sw
      
      TreeEntity treeEntity0 = new TreeEntity();
      
      //Call method: setParentName
      treeEntity0.setParentName("Sw");
      
      //Test Result Assert
      assertEquals("Sw", treeEntity0.getParentName());
  }
}
