/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.ruoyi.common.core.web.page;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.ruoyi.common.core.web.page.TableDataInfo;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class TableDataInfo_SSTest extends TableDataInfo_SSTest_scaffolding {
// allCoveredLines:[31, 32, 41, 42, 43, 44, 48, 53, 54, 58, 63, 64, 68, 73, 74, 78, 83, 84]

  @Test(timeout = 4000)
  public void test_getCode_0()  throws Throwable  {
      //caseID:dee4039fa4be35ee45e00dcfbb3a898a
      //CoveredLines: [41, 42, 43, 44, 68]
      //Assert: assertEquals(1221L, tableDataInfo0.getTotal());
      //Assert: assertEquals(0, method_result);
      
      Vector<Object> vector0 = new Vector<Object>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(vector0, 1221);
      
      //Call method: getCode
      int int0 = tableDataInfo0.getCode();
      
      //Test Result Assert
      assertEquals(1221L, tableDataInfo0.getTotal());
      
      //Test Result Assert
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test_getMsg_1()  throws Throwable  {
      //caseID:ff4d002ca0e54078c1e7eeaff57d8d78
      //CoveredLines: [41, 42, 43, 44, 78]
      //Assert: assertEquals((-1L), tableDataInfo0.getTotal());
      
      Stack<Object> stack0 = new Stack<Object>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(stack0, (-1));
      
      //Call method: getMsg
      tableDataInfo0.getMsg();
      
      //Test Result Assert
      assertEquals((-1L), tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_getRows_2()  throws Throwable  {
      //caseID:b36e2afc47748ed8fab90dd4421baa49
      //CoveredLines: [41, 42, 43, 44, 58]
      //Assert: assertEquals(0L, tableDataInfo0.getTotal());
      
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(arrayList0, 0);
      
      //Call method: getRows
      tableDataInfo0.getRows();
      
      //Test Result Assert
      assertEquals(0L, tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_getTotal_3()  throws Throwable  {
      //caseID:13df7a6651f5f31d8c4f0ece9928f609
      //CoveredLines: [31, 32, 48]
      //Assert: assertEquals(0L, method_result);
      
      TableDataInfo tableDataInfo0 = new TableDataInfo();
      
      //Call method: getTotal
      long long0 = tableDataInfo0.getTotal();
      
      //Test Result Assert
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test_setCode_4()  throws Throwable  {
      //caseID:e754417eb4efc402bb091c0b32c33808
      //CoveredLines: [31, 32, 73, 74]
      //Input_0_int: -67
      
      TableDataInfo tableDataInfo0 = new TableDataInfo();
      
      //Call method: setCode
      tableDataInfo0.setCode((-67));
      
      //Test Result Assert
      assertEquals((-67), tableDataInfo0.getCode());
  }

  @Test(timeout = 4000)
  public void test_setMsg_5()  throws Throwable  {
      //caseID:6af099ad40c3c237f6a2c1b96126a5ad
      //CoveredLines: [41, 42, 43, 44, 83, 84]
      //Input_0_String: 
      
      Stack<Integer> stack0 = new Stack<Integer>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(stack0, 0);
      
      //Call method: setMsg
      tableDataInfo0.setMsg("");
      
      //Test Result Assert
      assertEquals(0L, tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_setRows_6()  throws Throwable  {
      //caseID:2cf966c3a9cd441160ad6112659faf10
      //CoveredLines: [41, 42, 43, 44, 63, 64]
      //Input_0_List<?>: vector0
      
      Vector<String> vector0 = new Vector<String>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(vector0, 503);
      
      //Call method: setRows
      tableDataInfo0.setRows(vector0);
      
      //Test Result Assert
      assertEquals(503L, tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_setTotal_7()  throws Throwable  {
      //caseID:faea52b0cf34b74550c24a312ecd4825
      //CoveredLines: [41, 42, 43, 44, 53, 54]
      //Input_0_long: 1316
      
      Vector<Object> vector0 = new Vector<Object>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(vector0, 0);
      
      //Test Result Assert
      assertEquals(0L, tableDataInfo0.getTotal());
      
      
      //Call method: setTotal
      tableDataInfo0.setTotal(1316L);
      
      //Test Result Assert
      assertEquals(1316L, tableDataInfo0.getTotal());
  }
}
