/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.ruoyi.common.core.web.page;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.ruoyi.common.core.web.page.TableDataInfo;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class TableDataInfo_SSTest extends TableDataInfo_SSTest_scaffolding {
// allCoveredLines:[31, 32, 41, 42, 43, 44, 48, 53, 54, 58, 63, 64, 68, 73, 74, 78, 83, 84]

  @Test(timeout = 4000)
  public void test_getCode_0()  throws Throwable  {
      //caseID:2dceed380ed07f6e05a94579bdfef2fd
      //CoveredLines: [41, 42, 43, 44, 68]
      //Assert: assertEquals(0, method_result);
      //Assert: assertEquals(1446L, tableDataInfo0.getTotal());
      
      ArrayList<String> arrayList0 = new ArrayList<String>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(arrayList0, 1446);
      
      //Call method: getCode
      int int0 = tableDataInfo0.getCode();
      
      //Test Result Assert
      assertEquals(0, int0);
      
      //Test Result Assert
      assertEquals(1446L, tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_getMsg_1()  throws Throwable  {
      //caseID:b0472d91b4910acc57070c561dc56a6c
      //CoveredLines: [41, 42, 43, 44, 78]
      //Assert: assertEquals((-1L), tableDataInfo0.getTotal());
      
      Stack<Integer> stack0 = new Stack<Integer>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(stack0, (-1));
      
      //Call method: getMsg
      tableDataInfo0.getMsg();
      
      //Test Result Assert
      assertEquals((-1L), tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_getRows_2()  throws Throwable  {
      //caseID:bc6bd21046e7f33e7f7f20012931b9bd
      //CoveredLines: [41, 42, 43, 44, 58]
      //Assert: assertEquals((-1L), tableDataInfo0.getTotal());
      
      Stack<Integer> stack0 = new Stack<Integer>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(stack0, (-1));
      
      //Call method: getRows
      tableDataInfo0.getRows();
      
      //Test Result Assert
      assertEquals((-1L), tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_getTotal_3()  throws Throwable  {
      //caseID:2528b2f3a3550cc2e5f7e08f44748308
      //CoveredLines: [41, 42, 43, 44, 48]
      //Assert: assertEquals(107L, method_result);
      
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(arrayList0, 107);
      
      //Call method: getTotal
      long long0 = tableDataInfo0.getTotal();
      
      //Test Result Assert
      assertEquals(107L, long0);
  }

  @Test(timeout = 4000)
  public void test_setCode_4()  throws Throwable  {
      //caseID:b689e9fb3f66cb7a0d1efa9a4dc4799c
      //CoveredLines: [41, 42, 43, 44, 73, 74]
      //Input_0_int: -1
      
      Stack<Object> stack0 = new Stack<Object>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(stack0, (-1));
      
      //Call method: setCode
      tableDataInfo0.setCode((-1));
      
      //Test Result Assert
      assertEquals((-1), tableDataInfo0.getCode());
      
      //Test Result Assert
      assertEquals((-1L), tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_setMsg_5()  throws Throwable  {
      //caseID:19ae81bf2943d0245bfdc8ba377e9f0c
      //CoveredLines: [41, 42, 43, 44, 83, 84]
      //Input_0_String: 1
      
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(arrayList0, 0);
      
      //Call method: setMsg
      tableDataInfo0.setMsg("1");
      
      //Test Result Assert
      assertEquals(0L, tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_setRows_6()  throws Throwable  {
      //caseID:26bfb673f52562ba0d49c66ae150783a
      //CoveredLines: [41, 42, 43, 44, 63, 64]
      //Input_0_List<?>: arrayList0
      
      ArrayList<String> arrayList0 = new ArrayList<String>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(arrayList0, (-1));
      
      //Call method: setRows
      tableDataInfo0.setRows(arrayList0);
      
      //Test Result Assert
      assertEquals((-1L), tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_setTotal_7()  throws Throwable  {
      //caseID:98d6ccef150cb2ec945529fb3c330425
      //CoveredLines: [31, 32, 53, 54]
      //Input_0_long: 2048
      
      TableDataInfo tableDataInfo0 = new TableDataInfo();
      
      //Call method: setTotal
      tableDataInfo0.setTotal(2048);
      
      //Test Result Assert
      assertEquals(2048L, tableDataInfo0.getTotal());
  }

  @Test(timeout = 4000)
  public void test_setTotal_8()  throws Throwable  {
      //caseID:83c742a7b6e63f8e34ae659ec906cfa2
      //CoveredLines: [41, 42, 43, 44, 53, 54]
      //Input_0_long: 0
      
      Stack<String> stack0 = new Stack<String>();
      TableDataInfo tableDataInfo0 = new TableDataInfo(stack0, (-1074095546));
      
      //Test Result Assert
      assertEquals((-1074095546L), tableDataInfo0.getTotal());
      
      
      //Call method: setTotal
      tableDataInfo0.setTotal(0L);
      
      //Test Result Assert
      assertEquals(0, tableDataInfo0.getCode());
  }
}
